/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package speelotheek;

import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JUST_APPLE_031
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        MainJPanel = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        KindPanel = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        ActionPanel1 = new javax.swing.JPanel();
        btnToevoegen1 = new javax.swing.JButton();
        btnWijzigen1 = new javax.swing.JButton();
        btnVerwijderen1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        OuderPanel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ActionPanel = new javax.swing.JPanel();
        btnToevoegen = new javax.swing.JButton();
        btnWijzigen = new javax.swing.JButton();
        btnVerwijderen = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        LeningPanel = new javax.swing.JPanel();
        ActionPanel2 = new javax.swing.JPanel();
        btnToevoegen2 = new javax.swing.JButton();
        btnWijzigen2 = new javax.swing.JButton();
        btnVerwijderen2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        ScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        OmschrijvingPanel = new javax.swing.JPanel();
        ScrollPane3 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();
        ActionPanel3 = new javax.swing.JPanel();
        btnToevoegen3 = new javax.swing.JButton();
        btnWijzigen3 = new javax.swing.JButton();
        btnVerwijderen3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        SpeelgoedPanel = new javax.swing.JPanel();
        ScrollPane4 = new javax.swing.JScrollPane();
        Table4 = new javax.swing.JTable();
        ActionPanel4 = new javax.swing.JPanel();
        btnToevoegen4 = new javax.swing.JButton();
        btnWijzigen4 = new javax.swing.JButton();
        btnVerwijderen4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "naam", "ouder", "geslacht", "geboortedatum"
            }
        ));
        ScrollPane1.setViewportView(Table1);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(1).setHeaderValue("naam");
            Table1.getColumnModel().getColumn(2).setHeaderValue("ouder");
            Table1.getColumnModel().getColumn(3).setHeaderValue("geslacht");
            Table1.getColumnModel().getColumn(4).setHeaderValue("geboortedatum");
        }

        btnToevoegen1.setText("Toevoegen");

        btnWijzigen1.setText("Wijzigen");
        btnWijzigen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigen1ActionPerformed(evt);
            }
        });

        btnVerwijderen1.setText("Verwijderen");

        jTextField2.setToolTipText("");

        jButton5.setText("Zoeken");

        javax.swing.GroupLayout ActionPanel1Layout = new javax.swing.GroupLayout(ActionPanel1);
        ActionPanel1.setLayout(ActionPanel1Layout);
        ActionPanel1Layout.setHorizontalGroup(
            ActionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(ActionPanel1Layout.createSequentialGroup()
                        .addGroup(ActionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerwijderen1)
                            .addComponent(btnWijzigen1)
                            .addComponent(btnToevoegen1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActionPanel1Layout.setVerticalGroup(
            ActionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWijzigen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToevoegen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerwijderen1)
                .addGap(5, 5, 5)
                .addGroup(ActionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout KindPanelLayout = new javax.swing.GroupLayout(KindPanel);
        KindPanel.setLayout(KindPanelLayout);
        KindPanelLayout.setHorizontalGroup(
            KindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KindPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActionPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(KindPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPane1)))
                .addContainerGap())
        );
        KindPanelLayout.setVerticalGroup(
            KindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KindPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Kind", KindPanel);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "naam", "straat", "huisnr.", "woonplaats", "email", "telefoonnr.", "lidmaatschap begin", "lidmaatschap eind"
            }
        ));
        ScrollPane.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(1).setHeaderValue("naam");
            Table.getColumnModel().getColumn(2).setHeaderValue("straat");
            Table.getColumnModel().getColumn(3).setHeaderValue("huisnr.");
            Table.getColumnModel().getColumn(4).setHeaderValue("woonplaats");
            Table.getColumnModel().getColumn(5).setHeaderValue("email");
            Table.getColumnModel().getColumn(6).setHeaderValue("telefoonnr.");
            Table.getColumnModel().getColumn(7).setResizable(false);
            Table.getColumnModel().getColumn(7).setHeaderValue("lidmaatschap begin");
            Table.getColumnModel().getColumn(8).setResizable(false);
            Table.getColumnModel().getColumn(8).setHeaderValue("lidmaatschap eind");
        }

        btnToevoegen.setText("Toevoegen");

        btnWijzigen.setText("Wijzigen");

        btnVerwijderen.setText("Verwijderen");

        jTextField1.setToolTipText("");

        jButton4.setText("Zoeken");

        javax.swing.GroupLayout ActionPanelLayout = new javax.swing.GroupLayout(ActionPanel);
        ActionPanel.setLayout(ActionPanelLayout);
        ActionPanelLayout.setHorizontalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(ActionPanelLayout.createSequentialGroup()
                        .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerwijderen)
                            .addComponent(btnWijzigen)
                            .addComponent(btnToevoegen))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActionPanelLayout.setVerticalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWijzigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToevoegen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerwijderen)
                .addGap(5, 5, 5)
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout OuderPanelLayout = new javax.swing.GroupLayout(OuderPanel);
        OuderPanel.setLayout(OuderPanelLayout);
        OuderPanelLayout.setHorizontalGroup(
            OuderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OuderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        OuderPanelLayout.setVerticalGroup(
            OuderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Ouder", OuderPanel);

        btnToevoegen2.setText("Toevoegen");

        btnWijzigen2.setText("Wijzigen");

        btnVerwijderen2.setText("Verwijderen");

        jTextField3.setToolTipText("");

        jButton6.setText("Zoeken");

        javax.swing.GroupLayout ActionPanel2Layout = new javax.swing.GroupLayout(ActionPanel2);
        ActionPanel2.setLayout(ActionPanel2Layout);
        ActionPanel2Layout.setHorizontalGroup(
            ActionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(ActionPanel2Layout.createSequentialGroup()
                        .addGroup(ActionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerwijderen2)
                            .addComponent(btnWijzigen2)
                            .addComponent(btnToevoegen2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActionPanel2Layout.setVerticalGroup(
            ActionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWijzigen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToevoegen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerwijderen2)
                .addGap(5, 5, 5)
                .addGroup(ActionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "lid id", "speelgoed id", "uitleendatum", "geplande innamedatum", "innamedatum", "bijzonderheden"
            }
        ));
        ScrollPane2.setViewportView(Table2);

        javax.swing.GroupLayout LeningPanelLayout = new javax.swing.GroupLayout(LeningPanel);
        LeningPanel.setLayout(LeningPanelLayout);
        LeningPanelLayout.setHorizontalGroup(
            LeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActionPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane2)
                .addContainerGap())
        );
        LeningPanelLayout.setVerticalGroup(
            LeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Lening", LeningPanel);

        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "naam", "aantal onderdelen"
            }
        ));
        ScrollPane3.setViewportView(Table3);
        if (Table3.getColumnModel().getColumnCount() > 0) {
            Table3.getColumnModel().getColumn(1).setHeaderValue("naam");
            Table3.getColumnModel().getColumn(2).setHeaderValue("aantal onderdelen");
        }

        btnToevoegen3.setText("Toevoegen");

        btnWijzigen3.setText("Wijzigen");

        btnVerwijderen3.setText("Verwijderen");

        jTextField4.setToolTipText("");

        jButton7.setText("Zoeken");

        javax.swing.GroupLayout ActionPanel3Layout = new javax.swing.GroupLayout(ActionPanel3);
        ActionPanel3.setLayout(ActionPanel3Layout);
        ActionPanel3Layout.setHorizontalGroup(
            ActionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(ActionPanel3Layout.createSequentialGroup()
                        .addGroup(ActionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerwijderen3)
                            .addComponent(btnWijzigen3)
                            .addComponent(btnToevoegen3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActionPanel3Layout.setVerticalGroup(
            ActionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWijzigen3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToevoegen3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerwijderen3)
                .addGap(5, 5, 5)
                .addGroup(ActionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        javax.swing.GroupLayout OmschrijvingPanelLayout = new javax.swing.GroupLayout(OmschrijvingPanel);
        OmschrijvingPanel.setLayout(OmschrijvingPanelLayout);
        OmschrijvingPanelLayout.setHorizontalGroup(
            OmschrijvingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActionPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OmschrijvingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane3)
                .addContainerGap())
        );
        OmschrijvingPanelLayout.setVerticalGroup(
            OmschrijvingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OmschrijvingPanelLayout.createSequentialGroup()
                .addComponent(ActionPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Omschrijving speelgoed", OmschrijvingPanel);

        Table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "omschrijving id", "leeftijd id", "inkoopprijs", "inkoopdatum", "is uitgeleend"
            }
        ));
        ScrollPane4.setViewportView(Table4);

        btnToevoegen4.setText("Toevoegen");

        btnWijzigen4.setText("Wijzigen");

        btnVerwijderen4.setText("Verwijderen");

        jTextField5.setToolTipText("");

        jButton8.setText("Zoeken");

        javax.swing.GroupLayout ActionPanel4Layout = new javax.swing.GroupLayout(ActionPanel4);
        ActionPanel4.setLayout(ActionPanel4Layout);
        ActionPanel4Layout.setHorizontalGroup(
            ActionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(ActionPanel4Layout.createSequentialGroup()
                        .addGroup(ActionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerwijderen4)
                            .addComponent(btnWijzigen4)
                            .addComponent(btnToevoegen4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActionPanel4Layout.setVerticalGroup(
            ActionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWijzigen4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToevoegen4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerwijderen4)
                .addGap(5, 5, 5)
                .addGroup(ActionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        javax.swing.GroupLayout SpeelgoedPanelLayout = new javax.swing.GroupLayout(SpeelgoedPanel);
        SpeelgoedPanel.setLayout(SpeelgoedPanelLayout);
        SpeelgoedPanelLayout.setHorizontalGroup(
            SpeelgoedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeelgoedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpeelgoedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActionPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        SpeelgoedPanelLayout.setVerticalGroup(
            SpeelgoedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeelgoedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Speelgoed", SpeelgoedPanel);

        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);
        MainJPanel.setLayout(MainJPanelLayout);
        MainJPanelLayout.setHorizontalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        MainJPanelLayout.setVerticalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        TabbedPane.getAccessibleContext().setAccessibleName("Leden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWijzigen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigen1ActionPerformed

        
        String naam= JOptionPane.showInputDialog("naam");
        String ouder= JOptionPane.showInputDialog("ouder");
        String geslacht= JOptionPane.showInputDialog("geslacht");
        String geboortedatum= JOptionPane.showInputDialog("geboortedatum");

        SortedSet<Integer> set = new TreeSet<>();
        set.add(Integer.parseInt(naam));
        set.add(Integer.parseInt(ouder));
        set.add(Integer.parseInt(geslacht));
        set.add(Integer.parseInt(geboortedatum));

        Integer [] intArray = set.toArray(new Integer[3]);
        JFrame frame = new JFrame();
        JOptionPane.showInternalMessageDialog(frame.getContentPane(), String.format("Result %f", (intArray[1] + intArray[2]) / 2.0));
    
    }//GEN-LAST:event_btnWijzigen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JPanel ActionPanel1;
    private javax.swing.JPanel ActionPanel2;
    private javax.swing.JPanel ActionPanel3;
    private javax.swing.JPanel ActionPanel4;
    private javax.swing.JPanel KindPanel;
    private javax.swing.JPanel LeningPanel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JPanel OmschrijvingPanel;
    private javax.swing.JPanel OuderPanel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JScrollPane ScrollPane3;
    private javax.swing.JScrollPane ScrollPane4;
    private javax.swing.JPanel SpeelgoedPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table3;
    private javax.swing.JTable Table4;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnToevoegen1;
    private javax.swing.JButton btnToevoegen2;
    private javax.swing.JButton btnToevoegen3;
    private javax.swing.JButton btnToevoegen4;
    private javax.swing.JButton btnVerwijderen;
    private javax.swing.JButton btnVerwijderen1;
    private javax.swing.JButton btnVerwijderen2;
    private javax.swing.JButton btnVerwijderen3;
    private javax.swing.JButton btnVerwijderen4;
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JButton btnWijzigen1;
    private javax.swing.JButton btnWijzigen2;
    private javax.swing.JButton btnWijzigen3;
    private javax.swing.JButton btnWijzigen4;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
